# Generated by Django 3.2.25 on 2024-04-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='products',
            name='prodapp',
        ),
    ]
